CREATE DATABASE cfs;
USE cfs;

CREATE TABLE prod (
    pid INT AUTO_INCREMENT PRIMARY KEY,
    pname VARCHAR(100) NOT NULL,
    pdesc TEXT,
    price DECIMAL(10,2),
    img VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cust (
    cid INT AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50),
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fb (
    fid INT AUTO_INCREMENT PRIMARY KEY,
    pid INT,
    cid INT,
    rate INT CHECK (rate BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pid) REFERENCES prod(pid) ON DELETE CASCADE,
    FOREIGN KEY (cid) REFERENCES cust(cid) ON DELETE CASCADE
);
